// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoTTr.Format.PoTTr;

namespace PoTTr.Format.PoTTr.Migrations
{
    [DbContext(typeof(PoTTrContext))]
    partial class PoTTrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.ContentNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Begin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("MetadataId");

                    b.HasIndex("ParentId");

                    b.ToTable("ContentNode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MetadataId = 1,
                            NodeType = 5,
                            Order = 0u
                        });
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Metadata");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.Name", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NameType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.Agent", b =>
                {
                    b.HasOne("PoTTr.Format.PoTTr.Data.Metadata", "Metadata")
                        .WithMany("Agents")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.ContentNode", b =>
                {
                    b.HasOne("PoTTr.Format.PoTTr.Data.Agent", null)
                        .WithMany("ContentNodes")
                        .HasForeignKey("AgentId");

                    b.HasOne("PoTTr.Format.PoTTr.Data.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoTTr.Format.PoTTr.Data.ContentNode", "Parent")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("PoTTr.Format.PoTTr.Data.Name", b =>
                {
                    b.HasOne("PoTTr.Format.PoTTr.Data.Agent", "Agent")
                        .WithMany("Names")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
